var jwt = require('jsonwebtoken');
require('dotenv').config()
token1=process.env.CLERK_PEM_PUBLIC_KEY
console.log(token1)
jwt_token="eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18yaEpYWmVpTk5TMk9ZWUV1MWJoeFROdnZJWjgiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MTc3NDM1MTEsImlhdCI6MTcxNzc0MzQ1MSwiaXNzIjoiaHR0cHM6Ly9yZWxldmFudC12ZXJ2ZXQtNjIuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzE3NzQzNDQxLCJzaWQiOiJzZXNzXzJoWFZzbG5JUFBnNU5qTzlhOE1CZkFuaTJzYiIsInN1YiI6InVzZXJfMmhRWkdyTDRXdkNpbGo3OGF6Tkk4bFhxRGt6In0.agtcZpyBt7cvSCCuXiMZ_8V-Fgtm3xm5M7wwQdfePNnNg4aoBcDefP9Rsce3VpBE9OBehfwKuEGWAGPGATOzTgjUTseYqnVo3vMl4ogAjvJL769YNuHJaD47KC-BpAil_zuejNixjnXbVASRkzKxGgDwKOApPOAO6VOYtrKSyRNaLqm_3vjtflseqtHoJ1csddKXxkbi-RJoSfKpR72Vh-pB-akqtZu3a521yygkZgCxf4WQY-AgKr9jsUFC8pHPSltQD7Du1F6duq86EEkiTf6rMl2VdyRcA1Ilfh84KI2APjaUPDLjLCBtsxwOHwyhbQTRkgpk9Dvc_3hAoUqQ-Q"

const data=jwt.verify(jwt_token,token1,{ algorithms: ['RS256'] } );
console.log(data)